{% set name = "service_identity" %}
{% set version = "24.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8683ba13f0d39c6cd5d625d2c5f65421d6d707b013b375c355751557cbe8e09

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed . --verbose

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python
    - attrs >=19.1.0
    - pyasn1-modules
    - pyasn1
    - cryptography

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - service_identity
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/pyca/service_identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Service identity verification for pyOpenSSL.
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.io/en/stable/
  dev_url: https://github.com/pyca/service_identity

extra:
  recipe-maintainers:
    - isuruf
