{% set name = "service_identity" %}
{% set version = "18.1.0" %}
{% set sha256 = "0858a54aabc5b459d1aafa8a518ed2081a285087f349fe3e55197989232e2e2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: {{ noarch_python }}
  number: 0
  script: python -m pip install --no-deps --ignore-installed . --verbose

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - pyasn1
    - pyasn1-modules
    - pyopenssl >=0.12

test:
  imports:
    - service_identity

about:
  home: https://github.com/pyca/service_identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Service identity verification for pyOpenSSL.'
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.io/en/stable/
  dev_url: https://github.com/pyca/service_identity

extra:
  recipe-maintainers:
    - isuruf
