travis:
  secure:
    BINSTAR_TOKEN: uZcROQwURCErNrZcg+YADRq2auNo8k1CfHzave+Z7s2Uxh77ANNTNV9AXMwpPwZEvoD5dKpIaLj0cAvJtSOx7q7ihNiBjkePKmXKwpxIIvqpCmd0Xv84kZTXXrO4gMNfLheP7g6GZ9StYlc4E5RnoB70Q4MQ0LFPLXJAG6GIyk621lNXnOIw063AZexbTOLKtmdgQDUK6npBeFo9CJccH2cyhqiyWxCt1ib/0XMbDBggEGgfgCUzRVzJMO/vsqei+b/3IjKUPDI4ck91VEohgmZ8RzKoaQzFvxyvsQZUjyHAazeakbDWHbbfc8WSOfLwvtfuUZ5AwiEh9any2wqyn01oMlv/ax2buYZ1DbNwdyQ9H/pR7fhLIFZTj33P0H5RywKLLtl/rgPxK8+kcBiTw2zyhdIkVUipHxjFpXkdLE4ltZcZQJo889WPxVchmz+svfp6/oBLXgaJxP3IiGMWCdXddTeMljfhEv5Im9QKxdc/JDU6QhksTpH+q5IMVf74E/dgSXRI/c/mr9TbXcdxKIh1o7mP9BiZg+Nm1u/QTosVoG/MEyZqmSyOEq6H7bqMHjgeYZoj/6fhxpVQ+tsj+27vBjktto+yOBkk5wdVHoK95e3cTkgzYlOzoATQfLkHDw4ro4sFDyBybsqO1v7HROAiS2mIfLqUzP8evThx2kQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
