travis:
  secure:
    BINSTAR_TOKEN: sYspvL8lvXjN1vwKe+LNfxrmKyAOkpfusc3pyjV8C6ItAycSq4qY7HQbMy6CJ5OKmLuO1S5ooyZnjC2F2CkyIl2R5x0yihMbZSCJfSGhpWvK9x7xnPSH/t0IUJnC5mgDBr1K+XsPcjBW9BjNUaFazTYpknkGbyhHqPzamGuOn+SWfwKRYnsHEFbP9cAWcriWmxKPLvFbU9MqlixGUo8a2lxd/X/tXW6BxbRhEUijwFOAtR1m05XkXNHaL+xnbUUnaNePtTeQ4wr4F3gfIxvJxTwPSUxO/fiprLu16bV7yyT9obYw9dT5Hxa5YQZD3zfhq2zMBkJEa0mp+qM6bj1K+YS5at8tfL3nsHIiwvXaAMaaGH3m5oi/rWP9ksRujywz/cWCmDpps2rzylaQStKL/+c4Lk0bHKnk9Tyq/pzmyWmYoF5v88TH2Iwjtjgk86KVGi2nzwYpukUuTCpTlB99/eRS+kvLFG08gm9TSaAPXWMCE6rI0vHBvqJWH41j3uf3Fnf1YGrR4nOEOs6AjUpeonEoyFJp9iIWeoDLAqugNNQ1oIQHGDbc5RIW8a8++wGsi2rf4PEp49/1qzDgSpl9aTJJLfxDKD2HL1EKJpR0mtuB98fOo/r7V1DhJ333MMr2PJkjaVo1LkxQdrKykuE5cqK9XYclS1fhI1gJ4PkN+zM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
